### ISSUE TITLE
HTTP_X_FORWARDED_FOR gives a 'Why Blocked: Invalid IP!'

### ISSUE THREAD

**Issue by ArfurDent** [CIDRAM/CIDRAM#286]
I need to use HTTP_X_FORWARDED_FOR in my config.ini for Ezoic (Ad agency proxy) 

But I get a 'Why Blocked: Invalid IP!' blocked message for all page requests when 

ipaddr='HTTP_X_FORWARDED_FOR'

(The server gives an array of - correct - IP addresses for HTTP_X_FORWARDED_FOR as apposed to a single address)
I suspect this may be the issue, but I don't have the skills to investigate further.

**Comment by Maikuolan** [comment]
Thanks for reporting this. Working on a fix now. :-)

**Comment by Maikuolan** [comment]
Should be fixed now. Try updating, and let me know how it goes. :-)

**Comment by ArfurDent** [comment]
Thank you.
It still isn't working. 
I get two (correct) IPs separated by a comma in the 'Access Denied!' page.
and a Why Blocked: Invalid IP!
with ipaddr='HTTP_X_FORWARDED_FOR'



ID: 1643722175-391984-4010603747
Script Version: CIDRAM v2.8.0
Date/Time: Tue, 01 Feb 2022 13:29:35 +0000
IP Address: XX.XXX.XX.XX, XX.XXX.XX.XX
Signatures Count: 1
Signatures Reference: 
Why Blocked: Invalid IP!
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.66 Safari/537.36 X-Middleton/1
Reconstructed URI: https://xxxxxxx.com/CIDRAM/loader.php

**Comment by Maikuolan** [comment]
I've added some code just now to check for those separating commas. Hopefully that should do the trick. :-)

**Comment by ArfurDent** [comment]
I am running PHP version 7.4 (ea-php74) and I just get a blank white page for the latest CIDRAM fix
Apache Version is 2.4.52

**Comment by Maikuolan** [comment]
When you mention that you're just getting a blank white page, are we talking about when accessing the `loader.php` file *directly* (e.g., for attempting to access CIDRAM's front-end management features), or *indirectly* (e.g., accessing your website as per usual, with CIDRAM hooked via prepend, via `require`, `include`, etc)?

If we're talking *directly*: In your configuration (in your `vault/config.ini` file), there should be a configuration directive, `disable_frontend`. Do you currently have that configuration directive set as `true` or `false`? When `true`, if everything is working as intended (and assuming CIDRAM doesn't want to block the particular request in question), under normal circumstances, accessing the `loader.php` file directly should just show a blank white page (so, somewhat expected). When `false` (and also, when working as intended and accessing it directly), it should instead show the login page for the CIDRAM front-end.

Of course, when accessing it *indirectly* (e.g., via `require` or `include`), it shouldn't actually produce any output at all, seeing as we don't want CIDRAM interfering with whatever the website being protected would normally be trying to output. So, if we're talking *indirectly*, and yet it's producing just a blank white page (instead of what you would expect to be seeing normally when accessing your website as per usual), that would most likely indicate that something somewhere has broken (e.g., some problem introduced with a recent CIDRAM update, with the way CIDRAM has been hooked to the website, some previously undetected bug, or some other kind of problem).

**Comment by ArfurDent** [comment]
Thank you.

Now I feel silly. I was connecting to the loader directly because I had removed the hook while I was making the configuration changes and trying to see what I had done wrong.

my config.ini was set to disable_frontend=true 
which as you pointed out, gave me no output. 

So with disable_frontend=true set and accessing the loader.php directly, everything looks good. 

I will reinstate the hook and do some testing and report back.

Thank you for taking the time to sort this one out :)

**Comment by ArfurDent** [comment]
Of the two blocked while testing with CIDRAM hooked in, one had an IP address, the other was 'Invalid IP!'

ID: 1643895992-458317-1076936570
Script Version: CIDRAM v2.8.0
Date/Time: Thu, 03 Feb 2022 13:46:32 +0000
IP Address: unknown
Signatures Count: 1
Signatures Reference: 
Why Blocked: Invalid IP!
User Agent: GumGum-Bot/1.0 (http://gumgum.com; verity-support@gumgum.com) X-Middleton/1
Reconstructed URI: https://



ID: 1643891383-860931-2479549753
Script Version: CIDRAM v2.8.0
Date/Time: Thu, 03 Feb 2022 12:29:43 +0000
IP Address: 49.230.137.45
Referrer: https://www.google.co.th/
Signatures Count: 1
Signatures Reference: 49.228.0.0/14
Why Blocked: Attacks ("Phaholyothin Rd", L11527:F3, [TH])!
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1 X-Middleton/1
Reconstructed URI: https://

**Comment by Maikuolan** [comment]
> Thank you for taking the time to sort this one out :)

No problem at all, and thanks for getting back to me with the results of the changes to confirm how it went.

It's good to see that it seems to be at least *partially* working properly now (the latter blocked request), but it should definitely never have "unknown" listed as the IP address for a blocked request under normal circumstances (the former blocked request), so I guess, the bug hasn't been *entirely* fixed yet. In any case, progress, at least. :-)

*(For now, removing the "Fixed" label and adding the "Testing" label accordingly, seeing as this'll probably need some further investigation to properly get to the bottom of).*

About to get some sleep for the night, but I'll look into this again tomorrow and reply back again when I have a moment.

**Comment by Maikuolan** [comment]
Sorry for the delay. Past week has been busy with other things, and I haven't had any further progress on this issue yet, but replying briefly now, just to let you know that I haven't forgotten about it. :-)

**Comment by ArfurDent** [comment]
Thank you. 
Well, you could have thought that I would have a huge log of blocked IPs to check to search out anomalies but, I have been off Ezoic and ipaddr='REMOTE_ADDR' was set for the past week or so.

But as of today, I am back on Ezoic and ipaddr='HTTP_X_FORWARDED_FOR' so I can gather some logs.

**Comment by Maikuolan** [comment]
Currently reworking the way that CIDRAM handles IP address detection. I'll reply back again when it's ready to be pushed out as an update.

**Comment by Maikuolan** [comment]
I've pushed out an update regarding IP address resolution. It should hopefully work a little better now than before. :-)

**Comment by Maikuolan** [comment]
*Marking as fixed and closing.*
