### ISSUE TITLE
Moving the Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#356]
Hi,

Sometimes when i move up/down etc the Aux Rules, i see a Resend warning in my Firefox (and i select yes). Sometimes i don't see that message.

Is that normal? Seems kinda strange.

**Comment by Maikuolan** [comment]
I've never seen that happen before, so I'd wager that it's *not* normal. That said though, I don't use Firefox at my dev machine, so.. maybe a Firefox-specific behaviour, or some kind of Firefox-specific quirk..? I'm not sure.

Has anyone else here encountered this before?

**Comment by eurobank** [comment]
Here is the proof. Apart from the popup, nothing seems to be wrong.

![2022-11-14 15_25_22-CIDRAM – Auxiliary Rules — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/201671691-e5a07ca1-212d-41b6-abd6-866cee367d0c.png)

**Comment by Maikuolan** [comment]
Found the problem. The JavaScript I wrote which handles what happens when users click on the links provided for working with auxiliary rules uses `window.location.reload()` to tell the browser to reload the page after a successful response from CIDRAM:

https://github.com/CIDRAM/CIDRAM/blob/v3.0.0-beta2/vault/assets/frontend/default/auxiliary.js#L8-L12:
```JavaScript
function moveToTop(a, i) {
  window.auxT = a, $('POST', '', ['auxT'], null, function(a) {
    window.location.reload()
  })
}
```

*Technically*, per web standards, this is the correct thing to do. However, unfortunately, it seems Firefox does things differently than other browsers.

*Excerpt from __[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload)__:*
> ## Parameters
> None.
>
> __Note__: Firefox supports a non-standard `forceGet` boolean parameter for `location.reload()`, to tell Firefox to bypass its cache and force-reload the current document. However, in all other browsers, any parameter you specify in a `location.reload()` call will be ignored and have no effect of any kind.
>
> You may, though, come across instances of `location.reload(true)` in existing code that was written with the assumption the force-reload effect occurs in all browsers. A GitHub "`location.reload(true)`" search returns several hundred thousand results. So there's a lot of existing code which has it.

So, I may need to change it to using `window.location.reload(true)` instead (in theory, browsers other than Firefox should just ignore the additional parameter, and continue working the same as they were, while fixing the problem for Firefox).

Haven't tested this out yet, but about to do that now (and writing this detailed explanation here, instead of just fixing it directly, in case the change is questioned at some point in the future for some reason, to provide some context for the change).

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by eurobank** [comment]
Not resolved i'm afraid.

![2022-11-16 19_44_57-CIDRAM – Auxiliary Rules — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/202254798-59cfe507-81b8-487c-8bbe-a6dfb7bbde82.png)

**Comment by mikeruss1** [comment]
if its JS it maybe using the cached version. Try clearing the cache.

**Comment by eurobank** [comment]
> if its JS it maybe using the cached version. Try clearing the cache.

I have done that, CIDRAM's and of my browser.
