### ISSUE TITLE
BUG / Question ASN aux rules not been respected

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#429]
Is that 

"if the following condtions are met, block the request"

OR

"if **ONE OF** the following condtions are met, block the request"

not clear.
![Screenshot](https://user-images.githubusercontent.com/4467158/222985901-be57426e-ab2d-4968-bde9-0d68854334b9.png)

**Comment by eurobank** [comment]
The reason i'm asking is that something doesn't work right.

I have this rule:

![Screenshot](https://user-images.githubusercontent.com/4467158/222988334-7a7ac677-b4ef-477b-bab1-9679f05cd0cd.png)

BUT an IP that belongs to that ASN (the second listed) is NOT blocked:

ID: 1678053302-994140-3565036188 »
Date/Time: Sun, 05 Mar 2023 23:55:02 +0200 »
**IP address: 5.161.157.132** »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 »
Signatures count: 1 »
Signatures reference: 5.161.0.0/16 »
Why blocked: Cloud service ("Hetzner Online GmbH", L37393:F0, )! »

Infractions: 1 »
Country code lookup: US »
Request method: GET »
Hostname: static.132.157.161.5.clients.your-server.de »

**Comment by eurobank** [comment]
https://cleantalk.org/blacklists/5.161.157.132

belongs to as213230

BUT it is not blocked for that reason

![Screenshot](https://user-images.githubusercontent.com/4467158/222988563-7f8d32da-33ed-425e-9b1c-ac293e932626.png)


ID: 1678053302-994140-3565036188 »
Date/Time: Sun, 05 Mar 2023 23:55:02 +0200 »
IP address: 5.161.157.132 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 »
Signatures count: 1 »
Signatures reference: 5.161.0.0/16 »
Why blocked: Cloud service ("Hetzner Online GmbH", L37393:F0, )! »

Infractions: 1 »
Country code lookup: US »
Request method: GET »
Hostname: static.132.157.161.5.clients.your-server.de »

**Comment by mikeruss1** [comment]
it also uses this condition to define what you want

Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.
or
In order to trigger the rule, all conditions must be met.

**Comment by eurobank** [comment]
@mikeruss1 So my above aux rule should trigger if ANY of the two ASNs are validated? If so then it doesn't work.

**Comment by Maikuolan** [comment]
Looks like a type-casting bug. Working on a fix now.

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by eurobank** [comment]
Not fixed:

![Screenshot](https://user-images.githubusercontent.com/4467158/223101990-38dbe298-ef0e-40dd-9c82-5dc65c215103.png)


D: 1678102843-446898-4561965284 »
Date/Time: Mon, 06 Mar 2023 13:40:43 +0200 »
IP address: 51.83.213.191 »
User agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 »
Signatures count: 1 »
Signatures reference: 51.83.0.0/16 »
Why blocked: Cloud service ("OVH Systems", L13869:F1, )! »
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: ip191.ip-51-83-213.eu »


https://ipinfo.io/AS16276/51.83.0.0/16

**Comment by eurobank** [comment]
Maybe i get this wrong. BUT

IP 54.163.76.76 (AMAZON) belongs to ASN 14618, is that correct?

https://ipinfo.io/AS14618/54.160.0.0/14-54.163.76.0/22

I make an aux rule to block that ASN with direct compare but it is not blocked.

**Comment by eurobank** [comment]
Did some more accurate tests (my IP ASN) and definitely it doesn't seem to work.

**Comment by mikeruss1** [comment]
I always use Windows wild card option - give it a try?
start and end with an asterisk

**Comment by eurobank** [comment]
> I always use Windows wild card option - give it a try? start and end with an asterisk

Tried it, it doesn't seem to work.

**Comment by Maikuolan** [comment]
> start and end with an asterisk

Most other types of conditions should be fine, but I'd recommend against starting and ending ASN conditions with asterisks due to the risk of false positives.

If, for example, you wanted to block AS701 (Verizon Business), so set something like `*701*`, you'd also catch requests from AS7018 (AT&T Services, Inc), because the number "701" can be found in the number "7018".

**Comment by Maikuolan** [comment]
> IP 54.163.76.76 (AMAZON) belongs to ASN 14618, is that correct?

Yes, that's correct.

Investigating the problem now.

**Comment by Maikuolan** [comment]
Testing that Amazon IP address at my end, with an auxiliary rule to block ASN 14618, the IP address seems to be being blocked correctly. Maybe a typo somewhere in the rule itself? Mind showing me the data for the rule in question? Cheers.

**Comment by eurobank** [comment]
@Maikuolan Testing MY ip and my asn, doesn't block me. It seeme that asn blocks semi-work, since i see a FEW blocks from it. 

I have removed hostnames aux rules and set some asn (for OVH, for Digital Ocean, for Scaleway/ONLINE SAS, some russian ASNs, some China ASN) and my log is almost EMPTY.

**Comment by eurobank** [comment]
See my test and the Amazon test

![223205207-863b4814-9707-40c7-889f-0082e77f251e](https://user-images.githubusercontent.com/4467158/223409099-f41bf9dd-c1c4-4ec0-9878-1e13a857d5b0.png)

**Comment by eurobank** [comment]
Ok, i switched to bgpview for ip-api  and now it is blocking me !!

**Comment by eurobank** [comment]
This seems like a cache if cidram issue.

**Comment by eurobank** [comment]
Ok, still the same issue. Switching to bgpview for a while it worked, then not. Clearing the cache (all) worked for a while then not.

I was blocked twice, then not.

ID: 1678130237-619008-8734073361 »
Date/Time: Mon, 06 Mar 2023 21:17:17 +0200 »
IP address: xxxxxxxxxxx»
Query: cidram-page=logs&textMode=fancy&sortOrder=descending&remember=on&logfile=06-03-2023.log »
Referrer: https://xxxxxxxxxxxxxxxxxx/fe_cdr3.php?cidram-page=cache-data »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: TEST MY AS3329! »
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/fe_cdr3.php?cidram-page=logs&textMode=fancy&sortOrder=descending&remember=on&logfile=06-03-2023.log »
Infractions: 2 »
Country code lookup: GR »
Request method: GET »
Hostname:xxxxxxxxxxxxxxxxxxx »

**Comment by eurobank** [comment]
After a LOT of tests, it is not an issue of bpgview or ip-api but maybe some caching issue?

I can't debug this more, since no matter what i change, the result is inconsistent. Can't tell what is the cause, that is why i suspect the caching.

**Comment by eurobank** [comment]
This smells a lot like a caching issue of some kind.

**Comment by eurobank** [comment]
Here is an other one:

ASN Hetzner 

    The reason given to the user when blocked:
    ASN Hetzner
    HTTP status code override:
    403 Forbidden
    If the following conditions are met, block the request.
    ASN lookup = 24940
    ASN lookup = 213230
    Use direct string comparison to test the conditions.
    Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.

BUT:

ID: 1678179464-356400-6223258098 »
Date/Time: Tue, 07 Mar 2023 10:57:44 +0200 »
IP address: 116.202.85.79 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: reconstructed URLs! »
Reconstructed URI: /laravel/.env »
Infractions: 7 »
Country code lookup: XX »
Request method: GET »
Hostname: static.79.85.202.116.clients.your-server.de »

The above IP is https://ipinfo.io/AS24940/ BUT it was NOT blocked for that reason.

**Comment by eurobank** [comment]
In the above example, i see NO country code lookup, so ap-api was not accessed to check the ASN?

**Comment by eurobank** [comment]
Here is an other one:

ASN Scaleway-Online SAS-PoneyTelecom –
    The reason given to the user when blocked:
    ASN Scaleway-Online SAS-PoneyTelecom
    HTTP status code override:
    403 Forbidden
    If the following conditions are met, block the request.
    ASN lookup = 12876
    Use direct string comparison to test the conditions.
    Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.

--

ID: 1678200019-132773-0999626918 »
Date/Time: Tue, 07 Mar 2023 16:40:19 +0200 »
IP address: 163.172.213.212 »
Referrer: 
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0 »
Signatures count: 2 »
Signatures reference: 163.172.0.0/16, tor.php:L71 »
**Why blocked: Cloud service ("ONLINE S.A.S", L39538:F0, ), Tor exit node! »**
Reconstructed URI: https
Infractions: 2 »
Country code lookup: XX »
Request method: GET »
Hostname: trenecito.noconname.org

https://ipinfo.io/163.172.213.212

This was blocked for 2 reasons, TOR and Cloud service. How about my aux rules?

**Comment by eurobank** [comment]
@Maikuolan Could that be some issue (related or not)?

![Screenshot](https://user-images.githubusercontent.com/4467158/223525563-cdfd643f-702b-4fb7-baf6-eaf047b5296a.png)

**Comment by eurobank** [comment]
An other example. Same IP, first blocked for ASN & URL, then blocked ONLY for URL


ID: 1678272986-327083-8683962037 »
Date/Time: Wed, 08 Mar 2023 12:56:26 +0200 »
IP address: 45.91.20.108 »
User agent: - »
Signatures count: 2 »
Signatures reference: Core.php:L2132, Core.php:L2132 »
**Why blocked: GLOBAL ASNs_1, reconstructed URLs! »**
Reconstructed URI: /bak/www.tar »
Infractions: 2 »
Country code lookup: IT »
Request method: HEAD »
Hostname: - »


ID: 1678273681-685291-4042176858 »
Date/Time: Wed, 08 Mar 2023 13:08:01 +0200 »
IP address: 45.91.20.108 »
User agent: - »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
**Why blocked: reconstructed URLs! »**
Reconstructed URI: /sql.sql »
Infractions: 5 »
Country code lookup: XX »
Request method: HEAD »
Hostname: - »

**Comment by eurobank** [comment]
This is the last log i post, i think it is evident that something is wrong in ASN or in general. No more proof needed.

![2023-03-08 13_20_56-CIDRAM – Logs — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/223700923-43056f95-a304-43a5-a309-5782585915a6.png)

**Comment by eurobank** [comment]
i wonder, if there is a limit of # aux rules, conditions per rule ... that i have exceeded?

**Comment by Maikuolan** [comment]
> i wonder, if there is a limit of # aux rules, conditions per rule ... that i have exceeded?

Not by design or by intention (in theory, you should be able to have as many conditions and as many rules as you want). I'll investigate that as a potential bug or technical limitation though.

**Comment by eurobank** [comment]
> > i wonder, if there is a limit of # aux rules, conditions per rule ... that i have exceeded?
> 
> Not by design or by intention (in theory, you should be able to have as many conditions and as many rules as you want). I'll investigate that as a potential bug or technical limitation though.

For test reasons i have compacted a LOT, but no luck. So "size" doesn't seem to be the issue. Maybe checking multiple ASNs in one rule could be an issue.

**Comment by eurobank** [comment]
Using ip-api service.

I see some ASN is not respected and the IPs are blocked due to an other URL rule. I check the cache of IP-API and i see NO such IP, CIDR, ASN for that ip range. That means that probably IP-API is not contacted for some reason?

**Comment by Maikuolan** [comment]
> That means that probably IP-API is not contacted for some reason?

Possibly, that could be the case. I've sometimes noticed that BGPView fails to determine the ASN or country code for some specific IP addresses (no discernable pattern AFAICT; appears somewhat random as to which succeed and which fail), so perhaps IP-API suffers from the same problem (though I haven't encountered that particularly problem with IP-API before personally). I'll do some testing later tonight.

**Comment by eurobank** [comment]
"Sometimes" yeap i would accept that. But this is happening a lot, so it must be something else.

**Comment by eurobank** [comment]
This is one notorious APN that is ignored:


DNS Nameservers: ns2.digitalocean.com, ns1.digitalocean.com, ns3.digitalocean.com
Network owner: DigitalOcean LLC
**ASN #: 14061**

**Comment by eurobank** [comment]
Can i ask when the country lookup happens and when not? It will help me a lot to pinpoint issues.

**Comment by Maikuolan** [comment]
As long as there aren't currently any lookups in the cache for the IP address, a fresh lookup should occur for basically any request (and should then be immediately cached for any subsequent requests from the same IP address, up until the time that the cache entry expires).

**Comment by eurobank** [comment]
@Maikuolan If so, then definitelly something doesn't work right in lookups or lookups aren't "called" for some reason. 

I see a lot of XX.

**Comment by Maikuolan** [comment]
Yeah.. "XX" is the default placeholder value CIDRAM uses for country code lookups when it doesn't have any other data available (e.g., when there's nothing relevant in the cache, and no subsequent lookup has occurred, or, if a lookup has occurred, the lookup has failed to produce any usable data). So, one way or another, if modules capable of performing such lookups are installed and active, and despite that, we're still seeing "XX", that's a sign that something to do with lookups isn't working as intended.

**Comment by eurobank** [comment]
Then take a look at it, when you can. It is important.

**Comment by eurobank** [comment]
@Maikuolan 

Here are the results of your debug changes:

IP: 15.235.15.135 was not blocked (asn 16276):

![Screenshot](https://user-images.githubusercontent.com/4467158/225682418-8aa8671d-5b21-4998-b593-8fc8872ddce0.png)

--

![Screenshot (2)](https://user-images.githubusercontent.com/4467158/225682489-75d4063b-bcfb-4fe5-a998-97a9d5ee0f61.png)


But was blocked due to:

HostNames_1 – Hostname (ns5011471.ip-15-235-15.net) ≈ ns*.ip-*-*-*.net: Satisfied.

**Comment by Maikuolan** [comment]
I can see there that it's showing `ASN lookup (0)`, which means the ASN lookup isn't working correctly there at all (that "0" in the brackets, when ASN lookups are working correctly, instead of "0", should be showing the actual ASN like `ASN lookup (16276)`). I think the auxiliary rules are okay, but there's something bugged with the ASN lookup functionality. Debugging has definitely helped to get to this point here, I think. So, I think, I'll probably need to write something to allow us debug the actual lookup process, too (things like the status code for API lookup requests and such, which currently aren't logged anywhere). I suspect there might be something going on there that we'll need to look at.

**Comment by eurobank** [comment]
@Maikuolan Well, sometimes it works, sometimes not. I do see blocks due to ASN, but now always.

**Comment by eurobank** [comment]
@Maikuolan Can you please check this as a priority at somepoint? It is important ....

**Comment by eurobank** [comment]
Continued from here:

https://github.com/CIDRAM/CIDRAM/issues/445

**Comment by Maikuolan** [comment]
New debugging mechanism implemented. :-)

**Comment by eurobank** [comment]
ok, got it.

Question: Is that LAST request (GET -) correct? Several of those.


```
https://dns. google. com/resolve?name=17-241-219-179.applebot. apple.com&random_padding=UwQfYLM4Q2VCYe4gqPAIjE~.SEUv59.pMHMBZDYPKQuqLrtgg9bFg~_wXV9A927_T_1XD~TH9sfwAINDICa7HBM.lxjj_IPu2eeVD7ezKh~TEWlzRv1TgeIsm3Igm61eJnAG~SmNb-dX8AS1wak479vxuD7Z4eiWwCAjjUvurwa - 200 - 0.04s
[2023-03-25T12:55:16+0200] GET - https://api. bgpview. io/ip/88.239.101.94 - 200 - 0.97s
[2023-03-25T12:56:29+0200] GET - https://api. bgpview. io/ip/131.153.142.170 - 429 - 0.12s
[2023-03-25T12:56:29+0200] GET - https://api. bgpview. io/ip/131.153.240.2 - 200 - 0.68s
[2023-03-25T12:57:13+0200] GET - 
```

**Comment by eurobank** [comment]
Ok, i got a 429:

```
https://dns.google.com/resolve?name=17-241-219-179.applebot.apple.com&random_padding=UwQfYLM4Q2VCYe4gqPAIjE~.SEUv59.pMHMBZDYPKQuqLrtgg9bFg~_wXV9A927_T_1XD~TH9sfwAINDICa7HBM.lxjj_IPu2eeVD7ezKh~TEWlzRv1TgeIsm3Igm61eJnAG~SmNb-dX8AS1wak479vxuD7Z4eiWwCAjjUvurwa - 200 - 0.04s
[2023-03-25T12:55:16+0200] GET - https://api.bgpview.io/ip/88.239.101.94 - 200 - 0.97s
[2023-03-25T12:56:29+0200] GET - https://api.bgpview.io/ip/131.153.142.170 - **429** - 0.12s
[2023-03-25T12:56:29+0200] GET - https://api.bgpview.io/ip/131.153.240.2 - 200 - 0.68s
[2023-03-25T12:57:13+0200] GET - 
```

**Comment by eurobank** [comment]
This:

```
ID: 1679742782-206866-3245371917 »
Date/Time: Sat, 25 Mar 2023 13:13:02 +0200 »
IP address: 37.19.221.201 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 »
Signatures count: 1 »
Signatures reference: auxiliary.yml:HostNames Replaced with ASNs »
Why blocked: HostNames Replaced with ASNs! »
Reconstructed URI: xxxxxxxxxxxx
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: unn-37-19-221-201.datapacket.com »
```
Doesn't have a look up entry in the cache or debug log. Why could that be? No lookup?

**Comment by eurobank** [comment]
I see that google dns is used BUT i have changed that months ago:

![Screenshot(1)](https://user-images.githubusercontent.com/4467158/227715560-d3fe8c36-b930-425b-b3d1-f27971a65bdf.png)

**Comment by Maikuolan** [comment]
> I see that google dns is used BUT i have changed that months ago:

The `default_dns` values are used by the `dnsReverse()` method when performing UDP requests to fetch hostnames from IP addresses (meaning that, by changing the values for `default_dns`, Google DNS shouldn't ever be used for fetching hostnames from IP addresses), but the `dnsResolve()` method, which does the reverse of that (fetching IP addresses from hostnames, as part of the search engine and social media verification functionality), works by sending normal HTTP requests to Google DNS, and doesn't use `default_dns` at all.

Those HTTP requests to Google DNS *can* be forcibly disabled by checking the checkbox for "GoogleDNS" under `general➡disabled_channels`, which, in combination with the changed `default_dns` values, should totally prevent any communication to Google DNS from happening at all. I haven't yet coded in any alternative mechanisms for the `dnsResolve()` method to use though, so doing so would, at this point, also prevent CIDRAM from being able to resolve IP addresses from hostnames.

A long time ago (i.e., CIDRAM v1 days), I *had* implemented [`gethostbyname()`](https://www.php.net/gethostbyname) as a primary mechanism to resolve IP addresses from hostnames, but the effect that using `gethostbyname()` had on performance and overall load times was absolutely horrendous (adding, on average, about ~4 to ~5 seconds thereabouts to overall load times for affected pages, and in some rare cases, adding upwards of an entire minute to the overall load times for singular affected pages, rendering some affected websites with low timeout thresholds almost unusable). The effect it had on performance and overall load times, and the impossibility of modifying `gethostbyname()`'s behaviour (e.g., to add timeout values of our own, in order to facilitate an earlier, more elegant failure procedure in order to prevent the entire website request timing out, which.. if possible, would be something I'd love to see) is the main reason why I removed it entirely, opting to instead implement Google DNS as the primary mechanism for resolving IP addresses from hostnames (which, thankfully, provides the opportunity for us to specify our own timeouts). `gethostbyname()` also doesn't work properly for IPv6 (thus restricting potential lookups to IPv4 hostnames only).

I've yet to discover any other consistently reliable strategy for resolving IP addresses from hostnames, unfortunately. If I'm able to discover any at some point, I'll definitely implement them as an alternative to using Google DNS in that context.

**Comment by eurobank** [comment]
@Maikuolan Until the 429 issue is somehow resolved, how can i set a different pause of lookups? I mean instead of 4 hours. Where in the code is that part?

I would set it to something like 5 minutes, to limit the issue.

**Comment by Maikuolan** [comment]
> Doesn't have a look up entry in the cache or debug log. Why could that be? No lookup?

Seems to be the case. The newly implemented debugging mechanism for logging all outbound requests, assuming it has been enabled (which it has, given other stuff is being logged), as long as said outbound requests have been performed using CIDRAM's "request handler" (which handles all outgoing HTTP/S requests), has zero exceptions, no conditions under which it wouldn't log something. So, if something hasn't been logged, it either wasn't handled by the request handler (I mention this only because CIDRAM can sometimes perform other kinds of requests, like UDP requests performed when looking up IP addresses, which naturally aren't logged due to not being HTTP/S, though, such things have no relation whatsoever to country code lookups, so aren't something we need to worry about in this context), or, the request simply wasn't made at all in the first place.

**Comment by Maikuolan** [comment]
> Ok, i got a 429:

I guess that confirms it then: The service is legitimately attempting to rate limit your website's IP address. 429 might appear in the cache due to any non-200 status code appearing, but the outbound request log should always show only the actual, correct status code generated in response to the outbound request, so if the 429 is showing there, it's an actual 429.

The number of requests being sent from your websites to the service seems rather small though; Any idea whether it's a shared server or a dedicated server..? I can only speculate that maybe other people have websites hosted at the same server, with the same IP address, all similarly sending requests to the service.

> @Maikuolan Until the 429 issue is somehow resolved, how can i set a different pause of lookups? I mean instead of 4 hours. Where in the code is that part?
> 
> I would set it to something like 5 minutes, to limit the issue.

Sounds like that'll be the best solution here, I think. If there are other people at the same server, same IP address, which are hammering the service, we can't do anything about them, as we can only control ourselves, or whatever the case may be, if the service is trying to rate limit your website's IP address, dealing with that is probably our only realistic strategy.

The timeout for 429 cache entries isn't currently configurable, but I can easily change that. It's something that other CIDRAM users could probably benefit from too, so I'll work on that tonight. :-)

**Comment by Maikuolan** [comment]
> Where in the code is that part?

The specific lines in the code, for the BGPView module, is:

https://github.com/CIDRAM/CIDRAM/blob/202b3135dda2f4ae158193b790984f263ca2abe9/vault/modules/bgpview.php#L89

And for the IP-API module, is:

https://github.com/CIDRAM/CIDRAM/blob/202b3135dda2f4ae158193b790984f263ca2abe9/vault/modules/ipapi.php#L82

As a temporary measure, just changing that `14400` number (`14400` being the number of seconds in 4 hours) to something smaller should suffice. I'll make the value configurable shortly though.

**Comment by eurobank** [comment]
I'm on a premium shared plan. I don't believe it has anything to do with that, since bgpview AND ip-api are doing the exact same 429.

I will make those changes for now and see how it goes. Thanks for the help.

(thinking out loud: if a 429 is returned from the 1st api how about trying to the second api service? I mean if bgpview is sending 429, trying ip-api is available, and vice versa. Or that would slow things down .....)

**Comment by eurobank** [comment]
I see that ip-api has a 45 requests per minute limit. So that isn't happening from me, 100% sure about it. Now even if other sites hosted in that IP are accessing the api, 45 requests per minute is enough and wouldn't happen SO OFTEN (i mean almost in the 1st 5 minutes i'm clearing the cache).

**Comment by eurobank** [comment]
@Maikuolan 

Why two times request the same IP? And correctly get a 429 for the second?

```
[2023-03-25T07:08:28+0200] GET - https://api.bgpview.io/ip/66.249.90.2 - 200 - 0.84s
[2023-03-25T07:08:28+0200] GET - https://api.bgpview.io/ip/66.249.90.2 - 429 - 0.11s
```

**Comment by mikeruss1** [comment]
maybe the 45 requests per min is averaged over the minute, in other words you cant send another one within 1.3 secs ?

there is also this you may be breaking ....
The returned HTTP header X-Rl contains the number of requests remaining in the current rate limit window. X-Ttl contains the seconds until the limit is reset.
Your implementation should always check the value of the X-Rl header, and if its is 0 you must not send any more requests for the duration of X-Ttl in seconds.

**Comment by eurobank** [comment]
New data. I switched to IP-API to see what the log are when 429 happens.

It happened:

![Screenshot(1)](https://user-images.githubusercontent.com/4467158/227739501-19827f67-a24e-490e-9108-383e209dd2b7.png)

BUT there is no 429 error in the LOG. NONE. Instead i see this:

[2023-03-25T10:13:51+0200] GET - http://ip-api.com/json/95.161.221.125?fields=status,countryCode,as - 0 - 6s

a ZERO.

**Comment by eurobank** [comment]
and Status code 0 means unable to communicate with server via HTTP(s) ?

**Comment by Maikuolan** [comment]
> check the value of the X-Rl header

That's new information to me. I'll investigate that later today. Cheers. :-)

**Comment by Maikuolan** [comment]
> and Status code 0 means unable to communicate with server via HTTP(s) ?

Typically, yeah. A proper response from a webserver should always contain *some* kind of status code, whatever it may be. If it's showing zero, that would suggest that no response was received *at all*, so yeah.. probably unable to communicate with the server for whatever reason. Might be that they were down at the time, or routing failed, or something else.

Not a good thing, but should be a pretty rare occurrence.

**Comment by eurobank** [comment]
> > and Status code 0 means unable to communicate with server via HTTP(s) ?
> 
> Typically, yeah. A proper response from a webserver should always contain _some_ kind of status code, whatever it may be. If it's showing zero, that would suggest that no response was received _at all_, so yeah.. probably unable to communicate with the server for whatever reason. Might be that they were down at the time, or routing failed, or something else.
> 
> Not a good thing, but should be a pretty rare occurrence.

Not rare, 8 times in half a day.

**Comment by eurobank** [comment]
I see in the logs that ALL responses like this:

`[2023-03-26T09:31:05+0300] GET - http://ip-api.com/json/84.46.251.1?fields=status,countryCode,as - 0 - 12s`

(with zero) are 12seconds. 12 seconds is the timeout of CIDRAM for IP-API. So this could be an issue of slowness somewhere in the network or whatever. I will increase that for a 1-2 days to see what happens.

**Comment by eurobank** [comment]
@Maikuolan 

I think ALL related issues come from lookups like this:
```

[2023-03-26T01:03:55+0300] GET - https://api.bgpview.io/ip/167.160.73.72 - 429 - 0.07s
[2023-03-26T01:03:55+0300] GET - https://api.bgpview.io/ip/107.173.91.86 - 200 - 0.75s
```

Simultaneous or milliseconds around it, of lookups. How can we avoid 2 or more lookups at the very same time?

** Both IPs above are reported at Abusipdb with DDOS attacks **

**Comment by eurobank** [comment]
@Maikuolan 

Could that issue improve if i split ASNs from multiple in one rule, to one rule for eash ASN? What do you think?

**Comment by eurobank** [comment]
@Maikuolan 

I see in the lookups log MY ip (and probably others also) multiple times. Shouldn't those be cached and lookup only once?

![2023-03-26 15_12_25-CIDRAM – Logs — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/227774866-b629ad2c-6341-4c23-887e-6002bdec3317.png)

**Comment by mikeruss1** [comment]
just wondering if there is another way of doing this. If you are blocking a country like China, then get a list of all the IPs from one of the download sites and convert it to a signature file for CIDRAM to read.

or if its Amazon, Google cloud, Azure etc, modify the IPv4 signature file to do what you want.

also saves response time of ASN lookup

**Comment by eurobank** [comment]
@mikeruss1 

Well, this is getting hairy and i think i will drop all that asn and try to find an other way. Maybe i will again go back to hostnames but hostnames is blocking half of that i want.

**Comment by mikeruss1** [comment]
I have no problems with the IPv4 signature files. I dont need Amazon, Google cloud, Azure etc. Let alone Hetzner, Choopa and all the VPNs.

if I just get 1 signature block and its a Cloud signature I offer recaptcha in case its a valid VPN user. The vast majority of VPN blocks fail because they also have an outdated browser, invalid UA, or Http 1

**Comment by eurobank** [comment]
@mikeruss1 For me it is very different. ipv4 signatures are a no-go. I heavily rely to amazon, azure etc because a lot of advertizers use those.

For me it is better to let something pass, instead of a wrong block. But some ASNs are 100% unneeded and unwanted, like Digital Ocean's, Hetzner's, OVH's, Contabo's, etc etc.

**Comment by mikeruss1** [comment]
I thought the function of the bypasses was to stop that happening? Maybe that needs looking at? I stopped carrying ads a while ago as an experiment, no problem though in CIDRAM v2

in any event the source of the ASNs are clearly defined in IPv4, you could mod it?

**Comment by Maikuolan** [comment]
As an alternative to bypasses, if you happen to know the exact names of the sections of the exact offending signatures in the signature files, you can also opt to have those sections be ignored entirely by CIDRAM by clicking the "ignore this" link for that signatures section at the front-end sections list page.

**Comment by Maikuolan** [comment]
> I see in the lookups log MY ip (and probably others also) multiple times. Shouldn't those be cached and lookup only once?

Correct, they should be being cached and only looked up once. Maybe there are multiple concurrent requests happening at the same time, so by the time the first lookup occurs, but before CIDRAM has had time to cache the results yet, the second request has already begun, CIDRAM at the second requests checks the cache, doesn't find what it's looking for, so performs another lookup in that exact same moment, before anything has a chance to be cached? That's the only possibility that immediately comes to mind offhandedly, at least.

**Comment by mikeruss1** [comment]
I remember (I think) you are using PDO - if you were able to switch to Redis you may have less issues with cache contention

**Comment by eurobank** [comment]
@mikeruss1 Isn't better to debug each and every option and module available? Moving to something else and leave things as they are, doesn't seem the right thing to do.

**Comment by mikeruss1** [comment]
agreed, but if PDO caching is part of the problem I doubt if its fixable?

**Comment by eurobank** [comment]
> agreed, but if PDO caching is part of the problem I doubt if its fixable?

Well we abandoned memcached for some reason, we will abandon PDO for some (possible) reason, what else is left? Slowly we will switch away of CIDRAM also.

Why when we push a feature, it breaks? Maybe better testing is needed from more people. I dunno.

**Comment by mikeruss1** [comment]
been using Redis here with no problems. I did a lot of the beta testing, unfortunately I dont have ads so never saw your problem.

**Comment by eurobank** [comment]
> been using Redis here with no problems. I did a lot of the beta testing, unfortunately I dont have ads so never saw your problem.

Well REDIS is available for my hosting plan as one instance. So i'm already using it in some heavy Wordpress site. So i can only do limited test, switching WP off and CIDRAM on. On the other hand PDO is ... unlimited.

**Comment by mikeruss1** [comment]
see what Maikuolan thinks ?

**Comment by Maikuolan** [comment]
> I'll make the value configurable shortly though.

And done. :-)

Sorry for the delay. Had some other stuff to get done yesterday. Anyway, as of the current latest update, any modules which perform any outbound HTTP/S requests each now have a new directive, `timeout_rl`. That new directive can be used to adjust the expiry time for 429s for the affected modules.

**Comment by eurobank** [comment]
I don't think anything more can be done with this.
