### ISSUE TITLE
Opera (mobile) false positive?

### ISSUE THREAD

**Issue by tnovak007** [CIDRAM/CIDRAM#632]
Hi!

I think this is false positive for OperaMobile.

User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36 OPR/91.0.0.0
Signatures count: 1
Signatures reference: bobuam.php:L281
Why blocked: Masquerading attempt (TMOP)!
SEC_CH_UA_PLATFORM: "Android"
SEC_CH_UA_MOBILE: ?1
SEC_CH_UA: " Not;A Brand";v="99", "Chromium";v="139", "OperaMobile";v="91", "Opera";v="123"

It's probably triggering by the different Opera x OPR version, but the correct value is OperaMobil token.

```
    /** Fetch Opera user agent token. */
    if ($Opera = preg_match('%^(?=.*Mozilla\/).*OPR\/(\d+)\.\d+.*$%', $this->BlockInfo['UA'], $rebt)) {
        $TokenOpera = (int)$rebt[1];
    } else {
        $TokenOpera = 0;
    }
```
TokenOpera = 91

```

        if (isset($this->Tokens['Opera'])) {
            $Try = (int)$this->Tokens['Opera'];   <------ Tokens['Opera'] = 123; Tokens['OperaMobile'] = 91;
            if (
                $this->trigger($TokenOpera !== $Try, $Masquerade[0] . ' (TMOP)', $Masquerade[1]) ||
                $this->trigger($Try < 63, $Masquerade[0] . ' (FTOP)', $Masquerade[1])
            ) {
                $Failed = true;
            }
        }
```

Thanks.

**Comment by Maikuolan** [comment]
Nice catch; Cheers. :+1:

I'll get that sorted out shortly.

**Comment by Maikuolan** [comment]
Should be fixed now. :-)

**Comment by tnovak007** [comment]
Hi!

That was fast, thank you! ;-)

**Comment by tnovak007** [comment]
Hi!

I'm sorry to reopen this, but is seems the issue is still there. For Android users that are not identified as mobile...


User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 OPR/123.0.0.0
Signatures count: 1
Signatures reference: bobuam.php:L281
Why blocked: Masquerading attempt (TMOP)!
SEC_CH_UA_PLATFORM: "Android"
SEC_CH_UA_MOBILE: ?0
SEC_CH_UA: " Not;A Brand";v="99", "Chromium";v="139", "OperaMobile";v="91", "Opera";v="123"


So it seems it should check "Opera" value if UA_MOBILE is 0, even when "OperaMobile" is there too....

Thank you.

**Comment by Maikuolan** [comment]
No worries. Latest commits should (hopefully) fix the problem. :-)

**Comment by tnovak007** [comment]
Thank you again!
